# -*- coding: utf-8 -*-
"""LancetPH_Figure4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssMdH4K8iLAqC8JJXd-DZpCxukajo1P0

# Figure 4A
"""

from pathlib import Path

#outdir = Path("/mnt/data")
#outdir.mkdir(parents=True, exist_ok=True)

# Figure 4A. Early- and late-period climate-specific network structures
# Python code for data_merged_quarters.csv
#
# Input:
#   /content/drive/MyDrive/LancetPH/data_merged_quarters.csv
#
# Output:
#   /content/drive/MyDrive/LancetPH/figure/figure4A_network_structures.png
#   /content/drive/MyDrive/LancetPH/figure/figure4A_edge_status_table.csv
#   /content/drive/MyDrive/LancetPH/figure/figure4A_network_summary.csv
#
# Required:
#   pip install pandas numpy scipy networkx matplotlib
# ============================================================

from __future__ import annotations

from pathlib import Path
from itertools import combinations
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
from scipy.stats import pearsonr
import networkx as nx
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ------------------------------------------------------------
# 0. Paths
# ------------------------------------------------------------
BASE_PATH = Path("/content/drive/MyDrive/LancetPH")
DATA_FILE = BASE_PATH / "data_merged_quarters.csv"
FIGURE_PATH = BASE_PATH / "figure"
FIGURE_PATH.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# 1. Parameters
# ------------------------------------------------------------
EARLY_YEARS = [1990, 1995, 2000]
LATE_YEARS = [2010, 2015, 2018]

P_CUT = 0.05
R_CUT = 0.30

CLUSTERS = [1, 2, 3, 4, 5]

CLUSTER_TITLES = {
    1: "A1. Moderate climate–diet–disease coupling in a humid climate pattern\nC1: Temperate Humid",
    2: "A2. Sparse cross-domain coupling in a moderately arid climate pattern\nC2: Cold Humid",
    3: "A3. Increased climate–diet–disease coupling in a hot climate pattern\nC3: Warm Arid",
    4: "A4. Strongest and most intensified coupling in an extremely hot climate pattern\nC4: Extremely Hot",
    5: "A5. Limited climate–diet–disease coupling in a weakly connected climate pattern\nC5: Tropical Humid",
}

# Node order and domain definitions.
DIET_NODES = ["GDD1", "GDD2", "GDD3", "GDD4", "GDD5"]
DISEASE_NODES = ["GBD1", "GBD2", "GBD3", "GBD4", "GBD5"]
CLIMATE_NODES = ["PM25", "MeanT", "RH", "PR", "Heat_index"]

VARS = DIET_NODES + DISEASE_NODES + CLIMATE_NODES

DOMAIN = {v: "Diet" for v in DIET_NODES}
DOMAIN.update({v: "Disease" for v in DISEASE_NODES})
DOMAIN.update({v: "Climate" for v in CLIMATE_NODES})

DISPLAY_LABELS = {
    "MeanT": "Temperature",
    "RH": "Humidity",
    "PR": "Precipitation",
    "Heat_index": "Heat index",
    "PM25": "PM2.5",
}

NODE_COLORS = {
    "Climate": "#7BC87C",
    "Diet": "#E41A1C",
    "Disease": "#377EB8",
}

EDGE_COLORS = {
    "persistent": "#4D4D4D",
    "early_only": "#B0B0B0",
    "late_only": "#000000",
}

# fixed manual layout, shared across all panels
FIXED_POS = {
    "GDD1": (0.18, 0.68),
    "GDD2": (0.42, 0.48),
    "GDD3": (0.36, 0.12),
    "GDD4": (0.10, 0.85),
    "GDD5": (0.84, 0.58),
    "GBD1": (0.24, 0.58),
    "GBD2": (0.78, 0.34),
    "GBD3": (0.02, 0.34),
    "GBD4": (0.26, 0.34),
    "GBD5": (0.36, 0.22),
    "PM25": (0.84, 0.08),
    "MeanT": (0.08, 0.02),
    "RH": (0.95, 0.60),
    "PR": (0.02, 0.52),
    "Heat_index": (1.03, 0.22),
}


# ------------------------------------------------------------
# 2. Utility functions
# ------------------------------------------------------------
def read_csv_safely(path: Path) -> pd.DataFrame:
    encodings = ["utf-8-sig", "utf-8", "cp949", "euc-kr", "latin1"]
    last_error = None
    for enc in encodings:
        try:
            return pd.read_csv(path, encoding=enc)
        except UnicodeDecodeError as exc:
            last_error = exc
    raise RuntimeError(f"Could not read {path}. Last error: {last_error}")


def edge_key(a: str, b: str) -> Tuple[str, str]:
    return tuple(sorted([str(a), str(b)]))


def safe_pearson(x: pd.Series, y: pd.Series) -> Tuple[float, float]:
    x = pd.to_numeric(x, errors="coerce")
    y = pd.to_numeric(y, errors="coerce")
    mask = x.notna() & y.notna()
    x = x[mask]
    y = y[mask]
    if len(x) < 3 or x.nunique() <= 1 or y.nunique() <= 1:
        return np.nan, np.nan
    return pearsonr(x, y)


def make_edge_table(
    df: pd.DataFrame,
    years: Iterable[int],
    vars_: List[str] = VARS,
    p_cut: float = P_CUT,
    r_cut: float = R_CUT,
) -> pd.DataFrame:
    """Create significant correlation edge table for one time window."""
    sub = df.loc[df["year"].isin(years), vars_].copy()
    sub = sub.apply(pd.to_numeric, errors="coerce")

    rows = []
    for a, b in combinations(vars_, 2):
        r, p = safe_pearson(sub[a], sub[b])
        if pd.notna(r) and pd.notna(p) and p < p_cut and abs(r) >= r_cut:
            rows.append({
                "from": a,
                "to": b,
                "r": float(r),
                "p": float(p),
                "abs_r": float(abs(r)),
                "n": int(sub[[a, b]].dropna().shape[0]),
            })
    return pd.DataFrame(rows)


def compare_edges(early: pd.DataFrame, late: pd.DataFrame) -> pd.DataFrame:
    """Classify edges into persistent, early_only, late_only."""
    e0 = early.copy()
    e1 = late.copy()
    if e0.empty:
        e0 = pd.DataFrame(columns=["from", "to", "r", "p", "abs_r", "n"])
    if e1.empty:
        e1 = pd.DataFrame(columns=["from", "to", "r", "p", "abs_r", "n"])

    e0["key"] = [edge_key(a, b) for a, b in zip(e0["from"], e0["to"])]
    e1["key"] = [edge_key(a, b) for a, b in zip(e1["from"], e1["to"])]

    all_keys = sorted(set(e0["key"]).union(set(e1["key"])))

    rows = []
    e0_map = e0.set_index("key").to_dict(orient="index") if not e0.empty else {}
    e1_map = e1.set_index("key").to_dict(orient="index") if not e1.empty else {}

    for k in all_keys:
        in0 = k in e0_map
        in1 = k in e1_map
        if in0 and in1:
            status = "persistent"
        elif in0 and not in1:
            status = "early_only"
        else:
            status = "late_only"

        a, b = k
        r_early = e0_map.get(k, {}).get("r", np.nan)
        r_late = e1_map.get(k, {}).get("r", np.nan)

        rows.append({
            "from": a,
            "to": b,
            "status": status,
            "r_early": r_early,
            "r_late": r_late,
            "r_plot_early": r_early if in0 else np.nan,
            "r_plot_late": r_late if in1 else np.nan,
            "abs_r_plot_early": abs(r_early) if in0 and pd.notna(r_early) else np.nan,
            "abs_r_plot_late": abs(r_late) if in1 and pd.notna(r_late) else np.nan,
        })

    return pd.DataFrame(rows)


def network_summary(edge_status: pd.DataFrame, early: pd.DataFrame, late: pd.DataFrame) -> Dict[str, float]:
    """Calculate density, mean absolute association, and persistent percentage."""
    possible_edges = len(VARS) * (len(VARS) - 1) / 2

    early_n = len(early)
    late_n = len(late)
    early_density = early_n / possible_edges
    late_density = late_n / possible_edges

    early_mean = early["abs_r"].mean() if not early.empty else np.nan
    late_mean = late["abs_r"].mean() if not late.empty else np.nan

    persistent_n = int((edge_status["status"] == "persistent").sum()) if not edge_status.empty else 0
    union_n = int(len(edge_status))
    persistent_pct = 100 * persistent_n / union_n if union_n > 0 else np.nan

    return {
        "early_edges": early_n,
        "late_edges": late_n,
        "early_density": early_density,
        "late_density": late_density,
        "early_mean_abs_r": early_mean,
        "late_mean_abs_r": late_mean,
        "persistent_edges": persistent_n,
        "union_edges": union_n,
        "persistent_pct": persistent_pct,
    }


def node_degrees(edge_status: pd.DataFrame, period: str) -> Dict[str, int]:
    """Degree used for node size in early or late panel."""
    if edge_status.empty:
        return {v: 0 for v in VARS}

    if period == "early":
        edges = edge_status.loc[edge_status["r_plot_early"].notna()]
    else:
        edges = edge_status.loc[edge_status["r_plot_late"].notna()]

    deg = {v: 0 for v in VARS}
    for _, row in edges.iterrows():
        deg[row["from"]] += 1
        deg[row["to"]] += 1
    return deg


def draw_network(ax, edge_status: pd.DataFrame, period: str, title: str):
    """Draw early or late network panel."""
    ax.set_title(title, fontsize=9, fontstyle="italic")
    ax.axis("off")

    deg = node_degrees(edge_status, period)

    # Draw edges.
    for _, row in edge_status.iterrows():
        if period == "early" and pd.isna(row["r_plot_early"]):
            continue
        if period == "late" and pd.isna(row["r_plot_late"]):
            continue

        a, b = row["from"], row["to"]
        x0, y0 = FIXED_POS[a]
        x1, y1 = FIXED_POS[b]

        if row["status"] == "persistent":
            color = EDGE_COLORS["persistent"]
            alpha = 0.72
        elif row["status"] == "early_only":
            color = EDGE_COLORS["early_only"] if period == "early" else EDGE_COLORS["late_only"]
            alpha = 0.65 if period == "early" else 0.0
        else:
            color = EDGE_COLORS["late_only"] if period == "late" else EDGE_COLORS["early_only"]
            alpha = 0.80 if period == "late" else 0.0

        if alpha == 0:
            continue

        abs_r = row["abs_r_plot_early"] if period == "early" else row["abs_r_plot_late"]
        width = 0.4 + 2.6 * min(float(abs_r), 1.0)

        ax.plot([x0, x1], [y0, y1], color=color, alpha=alpha, linewidth=width, zorder=1)

    max_deg = max(max(deg.values()), 1)

    # Draw nodes.
    for node in VARS:
        x, y = FIXED_POS[node]
        dom = DOMAIN[node]
        color = NODE_COLORS[dom]
        size = 45 + 260 * (deg[node] / max_deg)

        ax.scatter(
            x, y,
            s=size,
            color=color,
            edgecolor="white",
            linewidth=0.7,
            alpha=0.92,
            zorder=3,
        )

        label = DISPLAY_LABELS.get(node, node)
        label_color = "#B0B0B0"
        fontweight = "bold"

        # Highlight visible nodes in current network.
        if deg[node] > 0:
            if dom == "Diet":
                label_color = "#E41A1C"
            elif dom == "Disease":
                label_color = "#0046D5"
            else:
                label_color = "#0046D5" if node in ["PR", "RH", "Heat_index", "MeanT", "PM25"] else "#222222"

        ax.text(
            x, y + 0.045,
            label,
            fontsize=7.2,
            color=label_color,
            ha="center",
            va="bottom",
            fontweight=fontweight,
            zorder=4,
        )

    ax.set_xlim(-0.10, 1.12)
    ax.set_ylim(-0.08, 1.03)


def draw_summary_box(ax, summary: Dict[str, float]):
    """Draw center summary box between early and late networks."""
    ax.axis("off")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)

    # background gradient-like blocks
    ax.axvspan(0.00, 0.50, color="#dbe9ff", alpha=0.75)
    ax.axvspan(0.50, 1.00, color="#ffe3dc", alpha=0.75)

    def fmt2(x):
        return "NA" if pd.isna(x) else f"{x:.2f}"

    def fmt0(x):
        return "NA" if pd.isna(x) else f"{x:.0f}"

    lines = [
        ("Density", fmt2(summary["early_density"]), fmt2(summary["late_density"])),
        ("Mean", fmt2(summary["early_mean_abs_r"]), fmt2(summary["late_mean_abs_r"])),
        ("Persistent", fmt0(summary["persistent_pct"]) + "%", ""),
    ]

    y_positions = [0.76, 0.51, 0.26]
    for (label, left, right), y in zip(lines, y_positions):
        ax.text(0.20, y, left, ha="center", va="center", fontsize=8, fontweight="bold")
        ax.annotate(
            "",
            xy=(0.72, y), xytext=(0.32, y),
            arrowprops=dict(arrowstyle="simple", color="black", lw=0.7),
        )
        if right:
            ax.text(0.82, y, right, ha="center", va="center", fontsize=8, fontweight="bold")
        ax.text(0.50, y - 0.10, label, ha="center", va="center", fontsize=8, fontweight="bold")


def make_cluster_networks(data: pd.DataFrame):
    """Create all edge status and summary tables."""
    required = ["year", "Climate_cluster_5"] + VARS
    missing = [c for c in required if c not in data.columns]
    if missing:
        raise KeyError(f"Missing columns: {missing}")

    data = data.copy()
    data["year"] = pd.to_numeric(data["year"], errors="coerce")
    data["Climate_cluster_5"] = pd.to_numeric(data["Climate_cluster_5"], errors="coerce")

    edge_tables = []
    summary_rows = []

    for cl in CLUSTERS:
        df_cl = data.loc[data["Climate_cluster_5"] == cl].copy()

        early = make_edge_table(df_cl, EARLY_YEARS)
        late = make_edge_table(df_cl, LATE_YEARS)
        status = compare_edges(early, late)

        if not status.empty:
            status.insert(0, "cluster", f"C{cl}")
            edge_tables.append(status)

        summ = network_summary(status, early, late)
        summ["cluster"] = f"C{cl}"
        summary_rows.append(summ)

    edge_all = pd.concat(edge_tables, ignore_index=True) if edge_tables else pd.DataFrame()
    summary_all = pd.DataFrame(summary_rows)

    return edge_all, summary_all


def create_figure4A(data_file: Path = DATA_FILE):
    data = read_csv_safely(data_file)
    edge_all, summary_all = make_cluster_networks(data)

    edge_all.to_csv(FIGURE_PATH / "figure4A_edge_status_table.csv", index=False, encoding="utf-8-sig")
    summary_all.to_csv(FIGURE_PATH / "figure4A_network_summary.csv", index=False, encoding="utf-8-sig")

    fig = plt.figure(figsize=(14.5, 15.2))
    gs = fig.add_gridspec(
        nrows=6,
        ncols=4,
        height_ratios=[0.35, 1, 1, 1, 1, 1],
        width_ratios=[1.25, 0.72, 1.25, 0.68],
        hspace=0.42,
        wspace=0.10,
    )

    title_ax = fig.add_subplot(gs[0, :])
    title_ax.axis("off")
    title_ax.text(
        0.00, 0.92,
        "Figure 4. Climate-specific temporal network structures of diet–disease–climate coupling",
        ha="left", va="top",
        fontsize=16, fontweight="bold",
    )
    title_ax.text(
        0.00, 0.20,
        "A. Early- and late-period climate-specific network structures",
        ha="left", va="top",
        fontsize=13, fontweight="bold",
    )

    for row_idx, cl in enumerate(CLUSTERS, start=1):
        ax_early = fig.add_subplot(gs[row_idx, 0])
        ax_box = fig.add_subplot(gs[row_idx, 1])
        ax_late = fig.add_subplot(gs[row_idx, 2])

        status = edge_all.loc[edge_all["cluster"] == f"C{cl}"].copy() if not edge_all.empty else pd.DataFrame()
        summ = summary_all.loc[summary_all["cluster"] == f"C{cl}"].iloc[0].to_dict()

        # Row title above the early panel.
        ax_early.text(
            -0.05, 1.10,
            CLUSTER_TITLES[cl],
            transform=ax_early.transAxes,
            ha="left", va="bottom",
            fontsize=10,
            fontweight="bold",
            fontfamily="serif",
        )

        draw_network(ax_early, status, "early", "Early Period (1990–2000)")
        draw_summary_box(ax_box, summ)
        draw_network(ax_late, status, "late", "Late Period (2010–2018)")

    # Legend panel
    ax_leg = fig.add_subplot(gs[1:3, 3])
    ax_leg.axis("off")

    y = 0.95
    ax_leg.text(0.0, y, "Node size =\nconnectivity (degree)", fontsize=9, fontweight="bold", va="top")
    y -= 0.18
    for domain, color in [("Climate", NODE_COLORS["Climate"]), ("Diet", NODE_COLORS["Diet"]), ("Disease", NODE_COLORS["Disease"])]:
        ax_leg.scatter(0.04, y, s=90, color=color)
        ax_leg.text(0.12, y, domain, fontsize=9, va="center")
        y -= 0.08

    y -= 0.05
    ax_leg.text(0.0, y, "Edge status:", fontsize=9, fontweight="bold", va="top")
    y -= 0.08

    edge_legend = [
        ("persistent\nedge present in both periods", EDGE_COLORS["persistent"], 1.8),
        ("early-only\nshown in LEFT panel", EDGE_COLORS["early_only"], 1.8),
        ("late-only\nshown in RIGHT panel", EDGE_COLORS["late_only"], 1.8),
    ]
    for label, color, width in edge_legend:
        ax_leg.plot([0.02, 0.22], [y, y], color=color, linewidth=width)
        ax_leg.text(0.25, y, label, fontsize=8, va="center")
        y -= 0.13

    y -= 0.03
    ax_leg.text(0.0, y, "edge width ∝ |r|", fontsize=8)
    y -= 0.12
    ax_leg.text(
        0.0, y,
        "Domain-level edge\nchanges\nDiet <-> Disease",
        fontsize=8.5,
        fontweight="bold",
        bbox=dict(boxstyle="round,pad=0.45", facecolor="#f7f7f7", edgecolor="#dddddd"),
        va="top",
    )

    out = FIGURE_PATH / "figure4A_network_structures.png"
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {out}")
    print(f"Saved: {FIGURE_PATH / 'figure4A_edge_status_table.csv'}")
    print(f"Saved: {FIGURE_PATH / 'figure4A_network_summary.csv'}")


if __name__ == "__main__":
    create_figure4A()

"""# Figure 4B"""

# ============================================================
# Figure 4B. Temporal trends in network coupling strength
# Python code for data_merged_quarters.csv
#
# Input:
#   /content/drive/MyDrive/LancetPH/data_merged_quarters.csv
#
# Output:
#   /content/drive/MyDrive/LancetPH/figure/figure4B_temporal_network_coupling_strength.png
#   /content/drive/MyDrive/LancetPH/figure/figure4B_coupling_strength_table.csv
#
# Required:
#   pip install pandas numpy scipy matplotlib
# ============================================================

from __future__ import annotations

from pathlib import Path
from itertools import combinations
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ------------------------------------------------------------
# 0. Paths
# ------------------------------------------------------------
BASE_PATH = Path("/content/drive/MyDrive/LancetPH")
DATA_FILE = BASE_PATH / "data_merged_quarters.csv"
FIGURE_PATH = BASE_PATH / "figure"
FIGURE_PATH.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# 1. Parameters
# ------------------------------------------------------------
YEARS = [1990, 1995, 2000, 2005, 2010, 2015, 2018]
EARLY_SPAN = (1990, 2000)
LATE_SPAN = (2010, 2018)

CLUSTERS = [1, 2, 3, 4, 5]

CLUSTER_LABELS = {
    1: "C1",
    2: "C2",
    3: "C3",
    4: "C4",
    5: "C5",
}

CLUSTER_COLORS = {
    1: "#1f78b4",
    2: "#59A14F",
    3: "#F28E2B",
    4: "#D62728",
    5: "#9467BD",
}

DIET_NODES = ["GDD1", "GDD2", "GDD3", "GDD4", "GDD5"]
DISEASE_NODES = ["GBD1", "GBD2", "GBD3", "GBD4", "GBD5"]
CLIMATE_NODES = ["PM25", "MeanT", "RH", "PR", "Heat_index"]
VARS = DIET_NODES + DISEASE_NODES + CLIMATE_NODES

COUPLING_MODE = "all_edges"
# Options:
#   "all_edges": mean absolute Pearson correlation across all node pairs
#   "cross_domain_only": mean absolute Pearson correlation only across different domains
#   "diet_disease_climate_only": diet-disease + climate-diet + climate-disease edges


# ------------------------------------------------------------
# 2. Utilities
# ------------------------------------------------------------
def read_csv_safely(path: Path) -> pd.DataFrame:
    encodings = ["utf-8-sig", "utf-8", "cp949", "euc-kr", "latin1"]
    last_error = None
    for enc in encodings:
        try:
            return pd.read_csv(path, encoding=enc)
        except UnicodeDecodeError as exc:
            last_error = exc
    raise RuntimeError(f"Could not read {path}. Last error: {last_error}")


def node_domain(v: str) -> str:
    if v.startswith("GDD"):
        return "Diet"
    if v.startswith("GBD"):
        return "Disease"
    return "Climate"


def pair_allowed(a: str, b: str, mode: str = COUPLING_MODE) -> bool:
    da = node_domain(a)
    db = node_domain(b)

    if mode == "all_edges":
        return True

    if mode == "cross_domain_only":
        return da != db

    if mode == "diet_disease_climate_only":
        pair = {da, db}
        return pair in [
            {"Diet", "Disease"},
            {"Diet", "Climate"},
            {"Disease", "Climate"},
        ]

    raise ValueError(f"Unknown COUPLING_MODE: {mode}")


def safe_pearson_abs(x: pd.Series, y: pd.Series) -> float:
    x = pd.to_numeric(x, errors="coerce")
    y = pd.to_numeric(y, errors="coerce")
    mask = x.notna() & y.notna()
    x = x[mask]
    y = y[mask]

    if len(x) < 3 or x.nunique() <= 1 or y.nunique() <= 1:
        return np.nan

    r, _ = pearsonr(x, y)
    return abs(r) if np.isfinite(r) else np.nan


def coupling_strength_for_subset(df: pd.DataFrame, vars_: List[str] = VARS, mode: str = COUPLING_MODE) -> Dict[str, float]:
    """Calculate mean absolute Pearson r for selected pairs."""
    values = []

    for a, b in combinations(vars_, 2):
        if not pair_allowed(a, b, mode):
            continue
        values.append(safe_pearson_abs(df[a], df[b]))

    values = np.array(values, dtype=float)
    values = values[np.isfinite(values)]

    if len(values) == 0:
        return {
            "mean_abs_r": np.nan,
            "median_abs_r": np.nan,
            "max_abs_r": np.nan,
            "n_pairs_valid": 0,
        }

    return {
        "mean_abs_r": float(np.mean(values)),
        "median_abs_r": float(np.median(values)),
        "max_abs_r": float(np.max(values)),
        "n_pairs_valid": int(len(values)),
    }


def compute_coupling_table(data: pd.DataFrame) -> pd.DataFrame:
    """Compute yearly coupling strength by climate cluster."""
    required = ["year", "Climate_cluster_5"] + VARS
    missing = [c for c in required if c not in data.columns]
    if missing:
        raise KeyError(f"Missing columns: {missing}")

    df = data.copy()
    df["year"] = pd.to_numeric(df["year"], errors="coerce")
    df["Climate_cluster_5"] = pd.to_numeric(df["Climate_cluster_5"], errors="coerce")

    rows = []

    for cl in CLUSTERS:
        for yr in YEARS:
            sub = df.loc[(df["Climate_cluster_5"] == cl) & (df["year"] == yr), VARS].copy()
            stats = coupling_strength_for_subset(sub, VARS, COUPLING_MODE)

            rows.append({
                "cluster": f"C{cl}",
                "cluster_num": cl,
                "year": yr,
                "n_countries": int(sub.dropna(how="all").shape[0]),
                **stats,
            })

    return pd.DataFrame(rows)


def draw_coupling_trends(coupling: pd.DataFrame):
    """Draw Figure 4B trend plot."""
    fig, ax = plt.subplots(figsize=(8.5, 4.2))

    # background periods
    ax.axvspan(EARLY_SPAN[0] - 0.5, EARLY_SPAN[1] + 0.5, color="#eaf2fb", alpha=0.85, zorder=0)
    ax.axvspan(LATE_SPAN[0] - 0.5, LATE_SPAN[1] + 0.5, color="#fdecea", alpha=0.85, zorder=0)

    for cl in CLUSTERS:
        sub = coupling.loc[coupling["cluster_num"] == cl].sort_values("year")
        ax.plot(
            sub["year"],
            sub["mean_abs_r"],
            marker="o",
            linewidth=2,
            markersize=4,
            color=CLUSTER_COLORS[cl],
            label=CLUSTER_LABELS[cl],
        )

        # Label cluster at last point.
        last = sub.dropna(subset=["mean_abs_r"]).tail(1)
        if len(last) > 0:
            ax.text(
                float(last["year"].iloc[0]) + 0.45,
                float(last["mean_abs_r"].iloc[0]),
                CLUSTER_LABELS[cl],
                color=CLUSTER_COLORS[cl],
                fontsize=10,
                fontweight="bold",
                va="center",
            )

    ax.set_title(
        "B. Temporal trends in network coupling strength",
        fontsize=13,
        fontweight="bold",
        loc="left",
    )
    ax.set_ylabel("Mean absolute association strength |Pearson r|", fontsize=10)
    ax.set_xlabel("")
    ax.set_xticks(YEARS)
    ax.set_xlim(min(YEARS) - 1, max(YEARS) + 2.5)

    ymin = coupling["mean_abs_r"].min(skipna=True)
    ymax = coupling["mean_abs_r"].max(skipna=True)
    if pd.isna(ymin) or pd.isna(ymax):
        ymin, ymax = 0, 1
    pad = 0.08 * (ymax - ymin if ymax > ymin else 1)
    ax.set_ylim(ymin - pad, ymax + pad)

    ax.grid(True, alpha=0.25)

    ax.text(
        np.mean(EARLY_SPAN),
        ymin - pad * 0.15,
        "Early period",
        ha="center",
        va="top",
        fontsize=9,
        style="italic",
        color="#555555",
    )
    ax.text(
        np.mean(LATE_SPAN),
        ymin - pad * 0.15,
        "Late period",
        ha="center",
        va="top",
        fontsize=9,
        style="italic",
        color="#555555",
    )

    # Narrative annotations
    c4 = coupling.loc[coupling["cluster_num"] == 4, "mean_abs_r"]
    if c4.notna().any():
        yr_max = coupling.loc[coupling["cluster_num"] == 4].sort_values("year").dropna(subset=["mean_abs_r"]).tail(1)
        if len(yr_max) > 0:
            ax.annotate(
                "C4: strongest / most intensified coupling",
                xy=(yr_max["year"].iloc[0], yr_max["mean_abs_r"].iloc[0]),
                xytext=(2004, yr_max["mean_abs_r"].iloc[0] + 0.04 * (ymax - ymin + 1e-9)),
                arrowprops=dict(arrowstyle="->", color=CLUSTER_COLORS[4], lw=1.2),
                color=CLUSTER_COLORS[4],
                fontsize=9,
                fontweight="bold",
            )

    ax.legend(loc="center left", bbox_to_anchor=(1.02, 0.5), frameon=False)
    fig.tight_layout()

    return fig


def create_figure4B(data_file: Path = DATA_FILE):
    data = read_csv_safely(data_file)
    coupling = compute_coupling_table(data)

    csv_path = FIGURE_PATH / "figure4B_coupling_strength_table.csv"
    coupling.to_csv(csv_path, index=False, encoding="utf-8-sig")

    fig = draw_coupling_trends(coupling)
    out = FIGURE_PATH / "figure4B_temporal_network_coupling_strength.png"
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved: {out}")
    print(f"Saved: {csv_path}")


if __name__ == "__main__":
    create_figure4B()

"""# Figure 4B': cross domain only"""

from pathlib import Path

# ============================================================
# Figure 4B. Temporal trends in cross-domain network coupling strength
# Python code for data_merged_quarters.csv
#
# Main difference from the previous all_edges version:
#   - This version uses ONLY cross-domain pairs.
#   - Included pairs:
#       Diet    <-> Disease
#       Diet    <-> Climate
#       Disease <-> Climate
#   - Excluded pairs:
#       Diet    <-> Diet
#       Disease <-> Disease
#       Climate <-> Climate
#
# Input:
#   /content/drive/MyDrive/LancetPH/data_merged_quarters.csv
#
# Output:
#   /content/drive/MyDrive/LancetPH/figure/figure4B_cross_domain_coupling_strength.png
#   /content/drive/MyDrive/LancetPH/figure/figure4B_cross_domain_coupling_strength_table.csv
#   /content/drive/MyDrive/LancetPH/figure/figure4B_cross_domain_pair_level_table.csv
#
# Required:
#   pip install pandas numpy scipy matplotlib
# ============================================================

from __future__ import annotations

from pathlib import Path
from itertools import combinations
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ------------------------------------------------------------
# 0. Paths
# ------------------------------------------------------------
BASE_PATH = Path("/content/drive/MyDrive/LancetPH")
DATA_FILE = BASE_PATH / "data_merged_quarters.csv"
FIGURE_PATH = BASE_PATH / "figure"
FIGURE_PATH.mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------
# 1. Parameters
# ------------------------------------------------------------
YEARS = [1990, 1995, 2000, 2005, 2010, 2015, 2018]
EARLY_SPAN = (1990, 2000)
LATE_SPAN = (2010, 2018)

CLUSTERS = [1, 2, 3, 4, 5]

CLUSTER_LABELS = {
    1: "C1",
    2: "C2",
    3: "C3",
    4: "C4",
    5: "C5",
}

CLUSTER_FULL_NAMES = {
    1: "C1 Temperate Humid",
    2: "C2 Cold Humid",
    3: "C3 Warm Arid",
    4: "C4 Extremely Hot",
    5: "C5 Tropical Humid",
}

CLUSTER_COLORS = {
    1: "#1f78b4",
    2: "#59A14F",
    3: "#F28E2B",
    4: "#D62728",
    5: "#9467BD",
}

DIET_NODES = ["GDD1", "GDD2", "GDD3", "GDD4", "GDD5"]
DISEASE_NODES = ["GBD1", "GBD2", "GBD3", "GBD4", "GBD5"]
CLIMATE_NODES = ["PM25", "MeanT", "RH", "PR", "Heat_index"]

VARS = DIET_NODES + DISEASE_NODES + CLIMATE_NODES

# Fixed mode: cross-domain only
COUPLING_MODE = "cross_domain_only"

# Optional: choose which statistic to plot.
# Recommended: "mean_abs_r"
PLOT_VALUE = "mean_abs_r"
# Other available values:
#   "median_abs_r"
#   "max_abs_r"

# Minimum number of countries needed in a year-cluster subset.
# Pearson correlation needs at least 3 observations.
MIN_N_COUNTRIES = 3


# ------------------------------------------------------------
# 2. Utilities
# ------------------------------------------------------------
def read_csv_safely(path: Path) -> pd.DataFrame:
    """
    Read CSV using common encodings.
    """
    encodings = ["utf-8-sig", "utf-8", "cp949", "euc-kr", "latin1"]
    last_error = None

    for enc in encodings:
        try:
            return pd.read_csv(path, encoding=enc)
        except UnicodeDecodeError as exc:
            last_error = exc

    raise RuntimeError(f"Could not read {path}. Last error: {last_error}")


def ensure_required_columns(df: pd.DataFrame, cols: List[str], label: str = "data") -> None:
    """
    Raise a clear error if required columns are missing.
    """
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise KeyError(f"Missing columns in {label}: {missing}")


def node_domain(v: str) -> str:
    """
    Return domain label for a node.
    """
    if v.startswith("GDD"):
        return "Diet"
    if v.startswith("GBD"):
        return "Disease"
    return "Climate"


def pair_type(a: str, b: str) -> str:
    """
    Return pair type such as Diet-Disease, Climate-Disease, etc.
    """
    da = node_domain(a)
    db = node_domain(b)

    if da == db:
        return f"{da}-{db}"

    return "-".join(sorted([da, db]))


def is_cross_domain_pair(a: str, b: str) -> bool:
    """
    Keep only pairs from different domains.
    """
    return node_domain(a) != node_domain(b)


def get_cross_domain_pairs(vars_: List[str] = VARS) -> List[Tuple[str, str]]:
    """
    Return all cross-domain variable pairs.
    """
    pairs = []

    for a, b in combinations(vars_, 2):
        if is_cross_domain_pair(a, b):
            pairs.append((a, b))

    return pairs


def safe_pearson_abs(x: pd.Series, y: pd.Series) -> Tuple[float, float, int]:
    """
    Safely calculate Pearson r and return |r|, r, and pairwise complete n.
    """
    x = pd.to_numeric(x, errors="coerce")
    y = pd.to_numeric(y, errors="coerce")

    mask = x.notna() & y.notna()
    x_use = x[mask]
    y_use = y[mask]
    n = int(mask.sum())

    if n < MIN_N_COUNTRIES:
        return np.nan, np.nan, n

    if x_use.nunique(dropna=True) <= 1 or y_use.nunique(dropna=True) <= 1:
        return np.nan, np.nan, n

    r, _ = pearsonr(x_use, y_use)

    if not np.isfinite(r):
        return np.nan, np.nan, n

    return abs(float(r)), float(r), n


def compute_pair_level_coupling(
    df_subset: pd.DataFrame,
    cluster_num: int,
    year: int,
    pairs: List[Tuple[str, str]],
) -> pd.DataFrame:
    """
    Calculate pair-level Pearson correlations for one cluster-year subset.
    """
    rows = []

    for a, b in pairs:
        abs_r, r, n_pair = safe_pearson_abs(df_subset[a], df_subset[b])

        rows.append({
            "cluster": f"C{cluster_num}",
            "cluster_num": cluster_num,
            "cluster_name": CLUSTER_FULL_NAMES[cluster_num],
            "year": year,
            "from": a,
            "to": b,
            "from_domain": node_domain(a),
            "to_domain": node_domain(b),
            "pair_type": pair_type(a, b),
            "r": r,
            "abs_r": abs_r,
            "n_pair_complete": n_pair,
        })

    return pd.DataFrame(rows)


def summarize_coupling(pair_tbl: pd.DataFrame) -> Dict[str, float]:
    """
    Summarize cross-domain pair-level |r| values.
    """
    vals = pd.to_numeric(pair_tbl["abs_r"], errors="coerce")
    vals = vals[np.isfinite(vals)]

    if len(vals) == 0:
        return {
            "mean_abs_r": np.nan,
            "median_abs_r": np.nan,
            "max_abs_r": np.nan,
            "n_pairs_total": int(len(pair_tbl)),
            "n_pairs_valid": 0,
        }

    return {
        "mean_abs_r": float(vals.mean()),
        "median_abs_r": float(vals.median()),
        "max_abs_r": float(vals.max()),
        "n_pairs_total": int(len(pair_tbl)),
        "n_pairs_valid": int(vals.shape[0]),
    }


def compute_cross_domain_coupling_tables(data: pd.DataFrame):
    """
    Compute cross-domain network coupling strength by climate cluster and year.

    Returns
    -------
    summary_table:
        One row per cluster-year.

    pair_level_table:
        One row per cluster-year-variable pair.
    """
    required = ["year", "Climate_cluster_5"] + VARS
    ensure_required_columns(data, required, "data_merged_quarters.csv")

    df = data.copy()
    df["year"] = pd.to_numeric(df["year"], errors="coerce")
    df["Climate_cluster_5"] = pd.to_numeric(df["Climate_cluster_5"], errors="coerce")

    pairs = get_cross_domain_pairs(VARS)

    summary_rows = []
    pair_tables = []

    for cl in CLUSTERS:
        for yr in YEARS:
            sub = df.loc[
                (df["Climate_cluster_5"] == cl)
                & (df["year"] == yr),
                VARS
            ].copy()

            n_countries = int(sub.dropna(how="all").shape[0])

            pair_tbl = compute_pair_level_coupling(
                df_subset=sub,
                cluster_num=cl,
                year=yr,
                pairs=pairs,
            )
            pair_tables.append(pair_tbl)

            stats = summarize_coupling(pair_tbl)

            summary_rows.append({
                "cluster": f"C{cl}",
                "cluster_num": cl,
                "cluster_name": CLUSTER_FULL_NAMES[cl],
                "year": yr,
                "n_countries": n_countries,
                "coupling_mode": COUPLING_MODE,
                **stats,
            })

    summary_table = pd.DataFrame(summary_rows)
    pair_level_table = pd.concat(pair_tables, ignore_index=True)

    return summary_table, pair_level_table


# ------------------------------------------------------------
# 3. Plot
# ------------------------------------------------------------
def draw_cross_domain_coupling_trends(coupling: pd.DataFrame):
    """
    Draw Figure 4B cross-domain coupling trend plot.
    """
    fig, ax = plt.subplots(figsize=(8.8, 4.5))

    # Period background
    ax.axvspan(
        EARLY_SPAN[0] - 0.5,
        EARLY_SPAN[1] + 0.5,
        color="#eaf2fb",
        alpha=0.85,
        zorder=0,
    )
    ax.axvspan(
        LATE_SPAN[0] - 0.5,
        LATE_SPAN[1] + 0.5,
        color="#fdecea",
        alpha=0.85,
        zorder=0,
    )

    for cl in CLUSTERS:
        sub = coupling.loc[coupling["cluster_num"] == cl].sort_values("year")

        ax.plot(
            sub["year"],
            sub[PLOT_VALUE],
            marker="o",
            linewidth=2.2 if cl == 4 else 1.8,
            markersize=4.5,
            color=CLUSTER_COLORS[cl],
            label=CLUSTER_LABELS[cl],
        )

        last = sub.dropna(subset=[PLOT_VALUE]).tail(1)
        if len(last) > 0:
            ax.text(
                float(last["year"].iloc[0]) + 0.45,
                float(last[PLOT_VALUE].iloc[0]),
                CLUSTER_LABELS[cl],
                color=CLUSTER_COLORS[cl],
                fontsize=10,
                fontweight="bold",
                va="center",
            )

    ax.set_title(
        "B. Temporal trends in cross-domain network coupling strength",
        fontsize=13,
        fontweight="bold",
        loc="left",
    )

    ax.set_ylabel("Mean absolute cross-domain association |Pearson r|", fontsize=10)
    ax.set_xlabel("")
    ax.set_xticks(YEARS)
    ax.set_xlim(min(YEARS) - 1, max(YEARS) + 2.6)

    ymin = coupling[PLOT_VALUE].min(skipna=True)
    ymax = coupling[PLOT_VALUE].max(skipna=True)

    if pd.isna(ymin) or pd.isna(ymax):
        ymin, ymax = 0, 1

    pad = 0.08 * (ymax - ymin if ymax > ymin else 1)
    ax.set_ylim(ymin - pad, ymax + pad)

    ax.grid(True, alpha=0.25)

    # Period labels
    ax.text(
        np.mean(EARLY_SPAN),
        ymin - pad * 0.20,
        "Early period",
        ha="center",
        va="top",
        fontsize=9,
        style="italic",
        color="#555555",
    )
    ax.text(
        np.mean(LATE_SPAN),
        ymin - pad * 0.20,
        "Late period",
        ha="center",
        va="top",
        fontsize=9,
        style="italic",
        color="#555555",
    )

    # Main annotation for C4
    c4 = coupling.loc[coupling["cluster_num"] == 4].dropna(subset=[PLOT_VALUE]).sort_values("year")

    if len(c4) > 0:
        last_c4 = c4.tail(1)
        ax.annotate(
            "C4: strongest cross-domain coupling",
            xy=(last_c4["year"].iloc[0], last_c4[PLOT_VALUE].iloc[0]),
            xytext=(2003.5, last_c4[PLOT_VALUE].iloc[0] + 0.06 * (ymax - ymin + 1e-9)),
            arrowprops=dict(arrowstyle="->", color=CLUSTER_COLORS[4], lw=1.2),
            color=CLUSTER_COLORS[4],
            fontsize=9,
            fontweight="bold",
        )

    # Moderate/stable annotation for lower clusters
    late_mean = (
        coupling.loc[coupling["year"].isin(LATE_SPAN), ["cluster_num", PLOT_VALUE]]
        .groupby("cluster_num")[PLOT_VALUE]
        .mean()
    )

    lower_clusters = [cl for cl in [1, 2, 5] if cl in late_mean.index]

    if lower_clusters:
        y_low = late_mean.loc[lower_clusters].mean()
        ax.text(
            2018.7,
            y_low,
            "C1/C2/C5:\nmoderate or stable",
            ha="left",
            va="center",
            fontsize=8.5,
            color="#444444",
        )

    handles = [
        Line2D(
            [0],
            [0],
            color=CLUSTER_COLORS[cl],
            marker="o",
            linewidth=2,
            label=f"{CLUSTER_LABELS[cl]}",
        )
        for cl in CLUSTERS
    ]

    ax.legend(
        handles=handles,
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        frameon=False,
        title="Climate cluster",
    )

    fig.tight_layout()

    return fig


# ------------------------------------------------------------
# 4. Main
# ------------------------------------------------------------
def create_figure4B_cross_domain(data_file: Path = DATA_FILE) -> None:
    """
    Create Figure 4B using cross-domain-only coupling strength.
    """
    print("Loading data...")
    data = read_csv_safely(data_file)
    print(f"Data shape: {data.shape}")

    print("Computing cross-domain coupling strength...")
    coupling, pair_level = compute_cross_domain_coupling_tables(data)

    summary_csv = FIGURE_PATH / "figure4B_cross_domain_coupling_strength_table.csv"
    pair_csv = FIGURE_PATH / "figure4B_cross_domain_pair_level_table.csv"

    coupling.to_csv(summary_csv, index=False, encoding="utf-8-sig")
    pair_level.to_csv(pair_csv, index=False, encoding="utf-8-sig")

    print("Drawing figure...")
    fig = draw_cross_domain_coupling_trends(coupling)

    out_png = FIGURE_PATH / "figure4B_cross_domain_coupling_strength.png"
    out_pdf = FIGURE_PATH / "figure4B_cross_domain_coupling_strength.pdf"

    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    fig.savefig(out_pdf, bbox_inches="tight")
    plt.close(fig)

    print("Saved:")
    print(out_png)
    print(out_pdf)
    print(summary_csv)
    print(pair_csv)


if __name__ == "__main__":
    create_figure4B_cross_domain()

!pip install pandas numpy scipy matplotlib

# !pip install pandas numpy scipy networkx matplotlib